apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jkp-tasks", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    name: jkp-tasks-pipeline
  name: jkp-tasks-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node() {
            stage 'build'
            openshiftBuild(buildConfig: 'jkp-tasks', showBuildLogs: 'true')

            stage 'deploy'
            openshiftDeploy(deploymentConfig: 'jkp-tasks')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: CzgPZAZ5m2
    type: GitHub
  - generic:
      secret: CzgPZAZ5m2
    type: Generic
